import { Assets, Spritesheet, Texture } from 'pixi.js'
import { MAP_TILE_IDS, type TileTextures } from './views/IslandsView'

const base = import.meta.env.BASE_URL

const GAME_BUNDLE = 'game'

const tileAlias = (id: number): string => `tile_${String(id)}`
const tileUrl = (id: number): string =>
  `${base}assets/png/default/tiles/tile_${String(id)}.png`

/**
 * Individual tile PNGs rather than sub-rectangles of tiles_sheet.png: at
 * fractional letterbox scales, neighbouring tiles in a sheet bleed into
 * each other and show up as seams.
 */
const gameManifest: Record<string, string> = {
  shipPlayer: `${base}assets/png/default/ships/ship_1.png`,
  // Distinct hull colours: Chasers ship_2, Shooters ship_3.
  shipChaser: `${base}assets/png/default/ships/ship_2.png`,
  shipShooter: `${base}assets/png/default/ships/ship_3.png`,
  water: tileUrl(73),
  // TexturePacker JSON-hash generated by `npm run atlas`; Assets detects
  // the format and resolves it to a Spritesheet (its PNG loads with it).
  shipsSheet: `${base}assets/spritesheet/ships_miscellaneous_sheet.json`,
  ...Object.fromEntries(MAP_TILE_IDS.map((id) => [tileAlias(id), tileUrl(id)])),
}

export interface GameTextures {
  shipPlayer: Texture
  shipChaser: Texture
  shipShooter: Texture
  water: Texture
  cannonBall: Texture
  muzzleFlash: Texture
  explosion: Texture
  tile: TileTextures
}

let bundleAdded = false
let pending: Promise<GameTextures> | null = null

// `instanceof Texture` alone narrows to Texture<any>; the guard keeps it typed.
function isTexture(value: unknown): value is Texture {
  return value instanceof Texture
}

function toGameTextures(loaded: Record<string, unknown>): GameTextures {
  const get = (alias: string): Texture => {
    const texture = loaded[alias]
    if (!isTexture(texture)) {
      throw new Error(`Texture "${alias}" missing from the game bundle`)
    }
    return texture
  }
  const sheet = loaded.shipsSheet
  if (!(sheet instanceof Spritesheet)) {
    throw new Error(
      'ships_miscellaneous_sheet.json did not load as a spritesheet',
    )
  }
  const frame = (name: string): Texture => {
    const texture = sheet.textures[name]
    if (!texture)
      throw new Error(`Frame "${name}" missing from the ships sheet`)
    return texture
  }
  return {
    shipPlayer: get('shipPlayer'),
    shipChaser: get('shipChaser'),
    shipShooter: get('shipShooter'),
    water: get('water'),
    cannonBall: frame('cannon_ball'),
    // The smallest explosion frame reads as a muzzle flash.
    muzzleFlash: frame('explosion_3'),
    explosion: frame('explosion_1'),
    tile: (id) => get(tileAlias(id)),
  }
}

/**
 * Loads the gameplay textures once and caches them for the lifetime of the page.
 * Textures are shared by every GameSession and are never destroyed on restart.
 */
export function loadGameAssets(): Promise<GameTextures> {
  if (!bundleAdded) {
    Assets.addBundle(GAME_BUNDLE, gameManifest)
    bundleAdded = true
  }
  pending ??= (
    Assets.loadBundle(GAME_BUNDLE) as Promise<Record<string, unknown>>
  )
    .then(toGameTextures)
    .catch((error: unknown) => {
      // Allow a later retry instead of caching the failure forever.
      pending = null
      throw error
    })
  return pending
}
